### ISSUE TITLE
It should report an error on unrecognized events

### ISSUE THREAD

**Issue by OmarTawfik** [OmarTawfik/workflow-parser-js#4]
From docs:
```
  # "on" identifies the event that will cause Actions to run this
  # workflow.  It's value is a double-quoted string, case-insensitive,
  # drawn from the list of known event types.
```
https://developer.github.com/actions/creating-workflows/workflow-configuration-options/#events-supported-in-workflow-files

**Comment by gr2m** [comment]
you could use https://github.com/octokit/webhooks as a start, we could make another one specifically for actions as their are some slight differences 🤔

**Comment by OmarTawfik** [comment]
@gr2m thanks for the suggestion! I'll look into it.
