### ISSUE TITLE
Feature Request: Format Document should be compatible with HCL's fmt

### ISSUE THREAD

**Issue by syntaqx** [OmarTawfik/workflow-parser-js#83]
After installing your extension I formatted the `main.workflow` in my project and got different output than that of `terraform fmt`.

Given GitHub actions use HCL, and Terraform is written by Hashicorp, I believe that the formatting output of your extension should be explicitly the same.

With `terraform fmt`:

```hcl
workflow "Example" {
  on       = "push"
  resolves = ["Go Modules"]
}

action "Go Modules" {
  uses = "actions-contrib/go@master"
  args = "mod download"
}
```

With VSCode's Format Document:

```hcl
workflow "Example" {
   on = "push"
   resolves = ["Go Modules"]
}

action "Go Modules" {
  uses = "actions-contrib/go@master"
  args = "mod download"
}
```

Notice the explicit indentation variations.

Also, great work on the extension so far. It's been much nicer to integrate with than the others I've tried.

**Comment by OmarTawfik** [comment]
Thanks a lot for looking into it!
I'll take a look at `terraform fmt` and see what I can do here.

**Comment by OmarTawfik** [comment]
Found a definition of that style:
https://www.terraform.io/docs/configuration/style.html
